#!/bin/bash --norc
#SBATCH --job-name=LigMPNN
#SBATCH --partition=gpu-a100          # <-- adjust to your cluster's GPU partition
#SBATCH --account=YOUR_ACCOUNT        # <-- replace with your SLURM account
#SBATCH --time=00:15:00
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --output=logs/out_ligandMPNN_%A_%a.out
#SBATCH --error=logs/err_ligandMPNN_%A_%a.err
#SBATCH --array=0-3   # NUM_RFD_TASKS * NUM_DESIGNS - 1  (e.g. 2 * 2 - 1 = 3)

set -euo pipefail

##############################################################################
# USER CONFIGURATION — edit these variables before submitting
##############################################################################

# Must match --array range in 1_RfDiff.sh  (e.g. 0-1 → 2 tasks)
NUM_RFD_TASKS=2

# Must match inference.num_designs in 1_RfDiff.sh
NUM_DESIGNS=2

# LigandMPNN runs per design
NUM_RUNS=10

# Path to your LigandMPNN installation
LIGMPNN_DIR=/path/to/LigandMPNN

# Path to the conda environment for LigandMPNN
LIGMPNN_ENV=/path/to/conda/envs/ligandmpnn_env

# Root directory for this project (same as PROJECT_DIR in 1_RfDiff.sh)
PROJECT_DIR=/path/to/your/project

# Space-separated list of residues to redesign (chain + residue number).
# These should cover the inserted loop generated by RFDiffusion.
# Example: residues 152-181 on chain A
REDESIGNED_RESIDUES="A152 A153 A154 A155 A156 A157 A158 A159 A160 A161 A162 A163 A164 A165 A166 A167 A168 A169 A170 A171 A172 A173 A174 A175 A176 A177 A178 A179 A180 A181"

##############################################################################

export TORCH_HOME=${LIGMPNN_DIR}/.cache

mkdir -p logs

module load conda/latest
eval "$(conda shell.bash hook)"
conda activate "${LIGMPNN_ENV}"

cd "${LIGMPNN_DIR}"

# Decode 2D index: SLURM_ARRAY_TASK_ID encodes (num1, num2)
num1=$(( SLURM_ARRAY_TASK_ID / NUM_DESIGNS ))   # RFDiffusion array task ID
num2=$(( SLURM_ARRAY_TASK_ID % NUM_DESIGNS ))   # design index within that task

pdb_file="${PROJECT_DIR}/outputs/${num1}_${num2}.pdb"
filename="${num1}_${num2}"

if [[ ! -f "$pdb_file" ]]; then
    echo "Error: $pdb_file not found."
    exit 1
fi

for i in $(seq 1 $NUM_RUNS); do
    out_folder="${PROJECT_DIR}/MPNN_outputs/${filename}_run${i}"

    python run.py \
        --model_type "ligand_mpnn" \
        --pdb_path "$pdb_file" \
        --out_folder "$out_folder" \
        --redesigned_residues "${REDESIGNED_RESIDUES}"
done
